name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: SumitMahajan11
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#39FF88&color_dots=#07130D,#0B3D24,#087F5B,#20C997,#8CE99A
            dist/github-contribution-grid-snake-dark.svg?color_snake=#39FF88&color_dots=#050B08,#0B3D24,#087F5B,#20C997,#8CE99A

      - name: Push output to snake-output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
